// ── plan selector prefill ────────────────────────────────
document.querySelectorAll('a[data-plan]').forEach((btn) => {
  btn.addEventListener('click', (e) => {
    e.preventDefault();
    document.getElementById('plan').value = btn.dataset.plan;
    document.getElementById('contact').scrollIntoView({ behavior: 'smooth' });
    setTimeout(() => document.getElementById('message').focus(), 600);
  });
});

// ── select: gold placeholder → ink after selection ────────
const planSelect = document.getElementById('plan');
if (planSelect) {
  planSelect.addEventListener('change', () => planSelect.classList.add('has-value'));
}

// ── carousel — photos auto-loaded from photos/ ────────────
(function () {
  const track = document.getElementById('carousel-track');
  const dotsEl = document.getElementById('carousel-dots');
  if (!track) return;

  // Full-size images (900w) — always present in build output
  const fullModules = import.meta.glob('./photos/*.{jpg,jpeg,png,webp,JPG,JPEG,PNG}', {
    eager: true,
  });
  // 450w thumbnails generated by scripts/resize-photos.js
  const smallModules = import.meta.glob('./photos/small/*.{webp,jpg,jpeg,png}', { eager: true });

  const fullEntries = Object.values(fullModules);

  if (fullEntries.length === 0) {
    track.closest('.carousel-wrap').style.display = 'none';
    return;
  }

  // Build a filename → small URL lookup (Vite hashes filenames, so match by original stem)
  // Key: "01-Felix_3-2" → hashed small URL
  const smallByName = {};
  Object.values(smallModules).forEach((m) => {
    const url = m.default;
    // Strip Vite hash suffix: "01-Felix_3-2-AbCdEf.webp" → "01-Felix_3-2"
    const stem = url
      .split('/')
      .pop()
      .replace(/\.[^.]+$/, '')
      .replace(/-[A-Za-z0-9]{8}$/, '');
    smallByName[stem] = url;
  });

  // carousel viewport: clamp(300px, 90vw, 900px); mobile: 98vw
  const SIZES = '(max-width: 540px) 98vw, clamp(300px, 90vw, 900px)';

  fullEntries.forEach((mod, i) => {
    const fullUrl = mod.default;
    const fullStem = fullUrl
      .split('/')
      .pop()
      .replace(/\.[^.]+$/, '')
      .replace(/-[A-Za-z0-9]{8}$/, '');
    const smallUrl = smallByName[fullStem];

    const slide = document.createElement('div');
    slide.className = 'carousel-slide';

    const img = document.createElement('img');
    img.src = fullUrl;
    img.alt = 'Pet being cared for by Yulia';
    img.width = 900;
    img.height = 600;

    if (smallUrl) {
      img.srcset = `${smallUrl} 450w, ${fullUrl} 900w`;
      img.sizes = SIZES;
    }

    if (i === 0) {
      img.loading = 'eager';
      img.fetchPriority = 'high';
      img.decoding = 'sync';
    } else {
      img.loading = 'lazy';
      img.decoding = 'async';
    }

    slide.appendChild(img);
    track.appendChild(slide);
  });

  const realSlides = Array.from(track.querySelectorAll('.carousel-slide'));
  const N = realSlides.length;
  if (N < 2) return;

  // Clone first and last for seamless infinite wrap
  const cloneFirst = realSlides[0].cloneNode(true);
  const cloneLast = realSlides[N - 1].cloneNode(true);
  cloneFirst.querySelector('img').loading = 'lazy';
  cloneLast.querySelector('img').loading = 'lazy';
  track.appendChild(cloneFirst);
  track.prepend(cloneLast);

  const total = N + 2;
  track.style.width = `${total * 100}%`;
  track.querySelectorAll('.carousel-slide').forEach((s) => {
    s.style.width = `${100 / total}%`;
  });

  let pos = 1;
  let transitioning = false;

  function setPos(n, animate) {
    track.style.transition = animate ? 'transform 0.55s cubic-bezier(0.4, 0, 0.2, 1)' : 'none';
    track.style.transform = `translateX(-${(n / total) * 100}%)`;
  }

  function updateDots(realIndex) {
    dotsEl.querySelectorAll('span').forEach((d, i) => {
      d.classList.toggle('active', i === realIndex);
    });
  }

  function goTo(newPos) {
    if (transitioning) return;
    transitioning = true;
    pos = newPos;
    setPos(pos, true);
    updateDots((((pos - 1) % N) + N) % N);
  }

  track.addEventListener('transitionend', () => {
    if (pos === 0) {
      pos = N;
      requestAnimationFrame(() =>
        requestAnimationFrame(() => {
          setPos(pos, false);
          transitioning = false;
        }),
      );
    } else if (pos === N + 1) {
      pos = 1;
      requestAnimationFrame(() =>
        requestAnimationFrame(() => {
          setPos(pos, false);
          transitioning = false;
        }),
      );
    } else {
      transitioning = false;
    }
  });

  realSlides.forEach((_, i) => {
    const dot = document.createElement('span');
    if (i === 0) dot.classList.add('active');
    dot.addEventListener('click', () => goTo(i + 1));
    dotsEl.appendChild(dot);
  });

  document.getElementById('carousel-prev').addEventListener('click', () => {
    clearInterval(timer);
    goTo(pos - 1);
  });
  document.getElementById('carousel-next').addEventListener('click', () => {
    clearInterval(timer);
    goTo(pos + 1);
  });

  const timer = setInterval(() => goTo(pos + 1), 3000);

  setPos(pos, false);
})();
